# Generated by Django 3.1.7 on 2021-07-20 17:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='사용자ID')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('contact', models.CharField(max_length=150, verbose_name='연락처')),
                ('birth', models.CharField(max_length=150, verbose_name='생년월일')),
                ('user_age', models.CharField(max_length=50, verbose_name='연령대')),
                ('gender', models.CharField(choices=[('여성', '여성'), ('남성', '남성'), ('기타', '기타')], max_length=2, verbose_name='성별')),
                ('balance', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='잔액')),
                ('registered_dtn', models.DateField(auto_now_add=True, verbose_name='가입일자')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('about', models.TextField(blank=True, verbose_name='소개말')),
                ('mode', models.CharField(choices=[('코디네이터', '코디네이터'), ('사용자', '사용자')], default='사용자', max_length=60, verbose_name='유저등급')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'TimeBank_user',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='거래일자')),
                ('mainwork', models.CharField(default='', max_length=100)),
                ('subwork', models.CharField(default='', max_length=100)),
                ('tok', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='거래금액')),
                ('giver_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='주는사람 잔액')),
                ('taker_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='받는사람 잔액')),
                ('giver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giver', to=settings.AUTH_USER_MODEL, verbose_name='주는사람')),
                ('taker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL, verbose_name='받는사람')),
            ],
        ),
    ]
