# Generated by Django 3.1.7 on 2021-07-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0001_initial'),
        ('TimeBank_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='TimeBank_app.post', verbose_name='거래글'),
        ),
    ]
