# Generated by Django 3.1.7 on 2021-07-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0004_auto_20210721_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('코디네이터', '코디네이터'), ('사용자', '사용자')], default='사용자', max_length=60, null=True, verbose_name='유저등급'),
        ),
    ]
