# Generated by Django 3.1.7 on 2021-07-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0005_auto_20210721_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='잔액'),
        ),
    ]
