# Generated by Django 3.1.7 on 2021-08-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0007_user_contactck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactCk',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
