# Generated by Django 3.1.7 on 2021-09-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0012_auto_20210919_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedproperty',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_properties', to='TimeBank_account.propertytag'),
        ),
    ]
