# Generated by Django 3.1.6 on 2021-09-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0010_auto_20210904_1340'),
        ('TimeBank_account', '0013_auto_20210919_1808'),
    ]

    operations = [
    ]
