# Generated by Django 3.1.7 on 2021-09-15 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_board', '0003_auto_20210907_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeBank_board.recomment'),
        ),
    ]
