# Generated by Django 3.1.7 on 2021-09-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_board', '0006_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='recomment',
            name='reply',
        ),
    ]
