# Generated by Django 3.1.7 on 2021-07-20 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='partner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='TimeBank_account.user', verbose_name='거래자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='후기작성자'),
        ),
    ]
