# Generated by Django 3.1.7 on 2021-07-30 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0006_auto_20210726_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='TimeBank_app.comment', verbose_name='댓글'),
        ),
    ]
