# Generated by Django 3.1.7 on 2021-08-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
