# Generated by Django 3.1.7 on 2021-08-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0010_auto_20210822_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='condition',
            field=models.CharField(choices=[('좋았어요', '좋았어요'), ('친절해요', '친절해요'), ('도움이 해결되었어요', '도움이 해결되었어요'), ('시간약속을 잘 지켰어요', '시간약속을 잘 지켰어요')], default='좋았어요', max_length=50, verbose_name='후기코멘트'),
        ),
    ]
