# Generated by Django 3.1.7 on 2021-08-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='date',
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='example', max_length=200, verbose_name='제목'),
        ),
    ]
