# Generated by Django 3.1.7 on 2021-09-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_board', '0002_auto_20210818_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='TimeBank_board.comment', verbose_name='댓글'),
        ),
    ]
