# Generated by Django 3.1.7 on 2021-09-15 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_board', '0004_recomment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rerecomment', to='TimeBank_board.recomment'),
        ),
    ]
