# Generated by Django 3.1.7 on 2021-09-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_board', '0007_auto_20210915_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='mention',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
