# Generated by Django 3.1.7 on 2021-03-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TimeBank_account', '0003_auto_20210312_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service', models.CharField(choices=[('give', '주고싶어요'), ('take', '받고싶어요')], max_length=50)),
                ('location', models.CharField(max_length=140)),
                ('content', models.CharField(help_text='최대 140자 입력 가능', max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeBank_account.user')),
            ],
        ),
    ]
