# Generated by Django 3.1.7 on 2021-04-19 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=140)),
                ('start_time', models.CharField(max_length=140)),
                ('end_time', models.CharField(max_length=140)),
                ('service', models.CharField(choices=[('주고싶어요', '주고싶어요'), ('받고싶어요', '받고싶어요')], max_length=50)),
                ('location', models.CharField(max_length=140)),
                ('main_work', models.CharField(max_length=140)),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('tok', models.PositiveIntegerField(default=0, verbose_name='거래톡')),
                ('status', models.CharField(choices=[('대기', '대기'), ('진행', '진행'), ('완료', '완료'), ('중단', '중단')], default='대기', max_length=50)),
                ('respond', models.CharField(choices=[('요청대기', '요청대기'), ('요청승인', '요청승인'), ('요청거절', '요청거절')], default='요청대기', max_length=50, verbose_name='승인상태')),
                ('applicants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeBank_app.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeBank_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
