# Generated by Django 3.1.7 on 2021-04-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='applicants',
            field=models.CharField(max_length=140, null=True, verbose_name='신청자'),
        ),
    ]
