# Generated by Django 3.1.7 on 2021-05-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0001_initial'),
        ('TimeBank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='TimeBank_account.account'),
        ),
    ]
