# Generated by Django 3.1.7 on 2021-06-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='applicants',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
