# Generated by Django 3.1.7 on 2021-05-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='account',
        ),
        migrations.RemoveField(
            model_name='post',
            name='account_no_from',
        ),
        migrations.RemoveField(
            model_name='post',
            name='account_no_to',
        ),
        migrations.AlterField(
            model_name='post',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_user', to='TimeBank_account.user', verbose_name='주는사람'),
        ),
        migrations.AlterField(
            model_name='post',
            name='taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_user', to='TimeBank_account.user', verbose_name='받는사람'),
        ),
    ]
