# Generated by Django 3.1.7 on 2021-04-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0002_auto_20210419_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='applicants',
        ),
        migrations.AlterField(
            model_name='post',
            name='tok',
            field=models.IntegerField(default=0, verbose_name='거래톡'),
        ),
    ]
