# Generated by Django 3.1.7 on 2021-06-21 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0002_auto_20210621_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applicants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL, verbose_name='지원자'),
        ),
    ]
