# Generated by Django 3.1.7 on 2021-04-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0002_messageitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageitem',
            options={'ordering': ['-pk'], 'verbose_name': '메세지함'},
        ),
    ]
