# Generated by Django 3.1.7 on 2021-05-21 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0002_auto_20210521_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='giver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_user', to=settings.AUTH_USER_MODEL, verbose_name='주는사람'),
        ),
        migrations.AlterField(
            model_name='post',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_user', to=settings.AUTH_USER_MODEL, verbose_name='받는사람'),
        ),
    ]
