# Generated by Django 3.1.7 on 2021-07-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0003_recomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
