# Generated by Django 3.1.7 on 2021-04-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0003_auto_20210423_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applicants',
            field=models.CharField(max_length=140, null=True, verbose_name='신청자'),
        ),
    ]
