# Generated by Django 3.1.7 on 2021-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0003_auto_20210521_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tok',
            field=models.FloatField(default=1, verbose_name='거래시간'),
        ),
    ]
