# Generated by Django 3.1.7 on 2021-04-05 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0003_auto_20210405_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageitem',
            options={'ordering': ['-pk'], 'verbose_name': '메세지함', 'verbose_name_plural': '메세지함 목록'},
        ),
        migrations.RemoveField(
            model_name='messageitem',
            name='active',
        ),
        migrations.AddField(
            model_name='messageitem',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageitem',
            name='status',
            field=models.CharField(choices=[('register', '신청하기'), ('register_complete', '신청완료'), ('wait', '대기중'), ('complete', '완료하기'), ('fail', '중단')], default='wait', max_length=50),
        ),
    ]
