# Generated by Django 3.1.7 on 2021-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0003_auto_20210319_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tok',
            field=models.PositiveIntegerField(default=0, verbose_name='거래톡'),
        ),
    ]
