# Generated by Django 3.1.7 on 2021-04-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0004_post_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='giver',
            field=models.CharField(max_length=140, null=True, verbose_name='주는사람'),
        ),
        migrations.AddField(
            model_name='post',
            name='taker',
            field=models.CharField(max_length=140, null=True, verbose_name='받는사람'),
        ),
    ]
