# Generated by Django 3.1.7 on 2021-05-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0005_auto_20210429_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
