# Generated by Django 3.1.7 on 2021-04-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0005_auto_20210405_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageitem',
            name='message_list',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
