# Generated by Django 3.1.7 on 2021-04-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0008_auto_20210405_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('신청하기', 'register'), ('신청완료', 'register_complete'), ('대기중', 'wait'), ('완료하기', 'complete'), ('중단', 'fail')], default='wait', max_length=50),
        ),
    ]
