# Generated by Django 3.1.7 on 2021-06-25 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0009_auto_20210622_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='applicants',
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('from_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_post', to='TimeBank_app.post')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_post', 'to_user')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='apply_user', through='TimeBank_app.Apply', to='TimeBank_app.Post'),
        ),
    ]
