# Generated by Django 3.1.7 on 2021-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0010_auto_20210625_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tok',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='거래시간'),
        ),
    ]
