# Generated by Django 3.1.7 on 2021-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0011_auto_20210405_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('wait', '대기'), ('progress', '진행'), ('complete', '완료'), ('fail', '중단')], default='wait', max_length=50),
        ),
    ]
