# Generated by Django 3.1.7 on 2021-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0011_review_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
