# Generated by Django 3.1.7 on 2021-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0012_auto_20210405_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('대기', '대기'), ('진행', '진행'), ('완료', '완료'), ('중단', '중단')], default='대기', max_length=50),
        ),
    ]
