# Generated by Django 3.1.7 on 2021-10-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0013_auto_20210908_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('MainCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeBank_app.category')),
            ],
            options={
                'unique_together': {('category_name',)},
            },
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mainwork',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subwork',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_category',
            field=models.CharField(blank=True, max_length=140, verbose_name='소분류'),
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeBank_app.category', verbose_name='대분류'),
        ),
    ]
