# Generated by Django 3.1.7 on 2021-04-05 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0014_auto_20210406_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='applicants',
        ),
        migrations.AddField(
            model_name='post',
            name='applicants',
            field=models.ManyToManyField(null=True, related_name='applier', to=settings.AUTH_USER_MODEL),
        ),
    ]
