# Generated by Django 3.1.7 on 2021-04-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0017_messageitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='respond',
            field=models.CharField(choices=[('요청대기', '요청대기'), ('요청승인', '요청승인'), ('요청거절', '요청거절')], default='요청대기', max_length=50, verbose_name='승인상태'),
        ),
    ]
