# Generated by Django 3.1.7 on 2021-04-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0018_auto_20210407_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='service',
            field=models.CharField(choices=[('주고싶어요', '주고싶어요'), ('받고싶어요', '받고싶어요')], max_length=50),
        ),
    ]
