# Generated by Django 3.1.7 on 2021-04-08 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0019_auto_20210407_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('from_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='신청글', to='TimeBank_app.post')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='지원자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
