# Generated by Django 3.1.7 on 2021-04-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0020_dealrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='applicants',
        ),
    ]
