# Generated by Django 3.1.7 on 2021-04-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0021_remove_post_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.CharField(max_length=140),
        ),
    ]
