# Generated by Django 3.1.7 on 2021-04-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0022_auto_20210412_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_work',
        ),
    ]
