# Generated by Django 3.1.7 on 2021-04-12 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeBank_app', '0023_remove_post_sub_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applier', through='TimeBank_app.MessageItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
