# Generated by Django 3.1.7 on 2021-04-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0024_post_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_work',
            field=models.CharField(max_length=140),
        ),
    ]
