# Generated by Django 3.1.7 on 2021-09-13 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='댓글등록시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopComment_author', to=settings.AUTH_USER_MODEL, verbose_name='댓글작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='답글등록시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopRecomment_author', to=settings.AUTH_USER_MODEL, verbose_name='답글작성자')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='TimeBank_timeshop.comment', verbose_name='댓글')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=140)),
                ('location', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('디지털기기', '디지털기기'), ('생활가전', '생활가전'), ('가구/인테리어', '가구/인테리어'), ('유아동', '유아동'), ('스포츠/레저', '스포츠/레저'), ('여성잡화', '여성잡화'), ('여성의류', '여성의류'), ('남성패션/잡화', '남성패션/잡화'), ('게임/취미', '게임/취미'), ('뷰티/미용', '뷰티/미용'), ('반려동물용품', '반려동물용품'), ('도서/티켓/음반', '도서/티켓/음반'), ('식물', '식물'), ('기타', '기타'), ('삽니다', '삽니다')], max_length=100, null=True)),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('tok', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='거래시간')),
                ('status', models.CharField(choices=[('대기', '대기'), ('진행', '진행'), ('완료', '완료'), ('완료확정', '완료확정'), ('중단', '중단')], default='대기', max_length=50)),
                ('respond', models.CharField(choices=[('요청대기', '요청대기'), ('요청승인', '요청승인'), ('요청거절', '요청거절')], default='요청대기', max_length=50, verbose_name='승인상태')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('applicants', models.ManyToManyField(blank=True, related_name='apply_user', through='TimeBank_timeshop.Deal', to='TimeBank_timeshop.Product')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='from_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_post', to='TimeBank_timeshop.product'),
        ),
        migrations.AddField(
            model_name='deal',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeBank_timeshop.product', verbose_name='글'),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('from_post', 'to_user')},
        ),
    ]
