# Generated by Django 3.1.7 on 2021-09-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_timeshop', '0002_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='mention',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
