# Generated by Django 3.1.7 on 2021-05-07 11:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='사용자ID')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('contact', models.CharField(max_length=150, verbose_name='연락처')),
                ('birth', models.CharField(max_length=150, verbose_name='생년월일')),
                ('user_age', models.CharField(max_length=50, verbose_name='연령대')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('balance', models.IntegerField(default=0, verbose_name='잔액')),
                ('registered_dtn', models.DateField(auto_now_add=True, verbose_name='가입일자')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'TimeBank_user',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록시간')),
                ('giver_balance', models.IntegerField(default=0, verbose_name='주는사람 계좌')),
                ('taker_balance', models.IntegerField(default=0, verbose_name='받는사람 계좌')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='시간계좌')),
                ('account_type', models.CharField(choices=[('주고싶어요', '주고싶어요'), ('받고싶어요', '받고싶어요')], max_length=10)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to=settings.AUTH_USER_MODEL, verbose_name='주는사람')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
