# Generated by Django 3.1.7 on 2021-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, verbose_name='사용자ID')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('contact', models.CharField(max_length=150, verbose_name='연락처')),
                ('birth', models.CharField(max_length=150, verbose_name='생년월일')),
                ('user_age', models.CharField(max_length=50, verbose_name='연령대')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('registered_dtn', models.DateField(auto_now_add=True, verbose_name='가입일자')),
            ],
            options={
                'db_table': 'TimeBank_user',
            },
        ),
    ]
