# Generated by Django 3.1.7 on 2021-05-20 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_no',
        ),
        migrations.AddField(
            model_name='account',
            name='giver',
            field=models.CharField(default='', max_length=100, verbose_name='주는사람'),
        ),
        migrations.AddField(
            model_name='account',
            name='mainwork',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='minus_tok',
            field=models.IntegerField(default=0, verbose_name='출금'),
        ),
        migrations.AddField(
            model_name='account',
            name='plus_tok',
            field=models.IntegerField(default=0, verbose_name='입금'),
        ),
        migrations.AddField(
            model_name='account',
            name='subwork',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='taker',
            field=models.CharField(default='', max_length=100, verbose_name='받는사람'),
        ),
        migrations.AddField(
            model_name='account',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='거래일자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
