# Generated by Django 3.1.7 on 2021-05-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0002_auto_20210524_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
