# Generated by Django 3.1.7 on 2021-03-12 07:31

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0002_user_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
