# Generated by Django 3.1.7 on 2021-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0003_remove_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='minus_tok',
        ),
        migrations.RemoveField(
            model_name='account',
            name='plus_tok',
        ),
        migrations.AddField(
            model_name='account',
            name='tok',
            field=models.IntegerField(default=0, verbose_name='거래금액'),
        ),
    ]
