# Generated by Django 3.1.7 on 2021-05-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0003_auto_20210419_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='time_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='state_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transfer_balance',
        ),
    ]
