# Generated by Django 3.1.7 on 2021-03-23 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0003_auto_20210312_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_type', models.CharField(choices=[('deal', '거래진행중'), ('request', '요청진행중'), ('complete', '거래완료'), ('inquire', '요청보내기')], max_length=10, verbose_name='요청상태')),
                ('account_no', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('transfer_number', models.IntegerField(default=3)),
                ('bank', models.CharField(max_length=10)),
                ('account_type', models.CharField(choices=[('give', '주고싶어요'), ('take', '받고싶어요')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeBank_account.user')),
            ],
        ),
    ]
