# Generated by Django 3.1.7 on 2021-03-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0004_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transfer_number',
        ),
        migrations.AddField(
            model_name='account',
            name='time_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='시간계좌'),
        ),
        migrations.AddField(
            model_name='account',
            name='transfer_balance',
            field=models.IntegerField(default=0, verbose_name='시간거래활동'),
        ),
    ]
