# Generated by Django 3.1.7 on 2021-05-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_app', '0006_delete_register'),
        ('TimeBank_account', '0004_auto_20210503_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록시간'),
        ),
        migrations.AddField(
            model_name='account',
            name='giver',
            field=models.CharField(max_length=50, null=True, verbose_name='주는사람'),
        ),
        migrations.AddField(
            model_name='account',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transfer', to='TimeBank_app.post'),
        ),
        migrations.AddField(
            model_name='account',
            name='taker',
            field=models.CharField(max_length=50, null=True, verbose_name='받는사람'),
        ),
    ]
