# Generated by Django 3.1.7 on 2021-06-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0005_auto_20210524_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, verbose_name='잔액'),
        ),
    ]
