# Generated by Django 3.1.7 on 2021-05-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0005_auto_20210505_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('주고싶어요', '주고싶어요'), ('받고싶어요', '받고싶어요')], max_length=10),
        ),
    ]
