# Generated by Django 3.1.7 on 2021-06-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0006_auto_20210621_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여성', '여성'), ('남성', '남성'), ('기타', '기타')], max_length=2, verbose_name='성별'),
        ),
    ]
