# Generated by Django 3.1.7 on 2021-03-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0006_auto_20210327_0643'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
