# Generated by Django 3.1.7 on 2021-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0006_auto_20210505_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='giver_balance',
            field=models.IntegerField(default=0, verbose_name='주는사람 계좌'),
        ),
        migrations.AddField(
            model_name='account',
            name='taker_balance',
            field=models.IntegerField(default=0, verbose_name='받는사람 계좌'),
        ),
    ]
