# Generated by Django 3.1.7 on 2021-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0007_auto_20210327_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, verbose_name='이름'),
        ),
    ]
