# Generated by Django 3.1.7 on 2021-06-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0007_auto_20210625_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tok',
            field=models.FloatField(default=0, verbose_name='거래금액'),
        ),
    ]
