# Generated by Django 3.1.7 on 2021-03-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0008_auto_20210330_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userid',
        ),
    ]
