# Generated by Django 3.1.7 on 2021-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0008_auto_20210625_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=10, verbose_name='잔액'),
        ),
    ]
