# Generated by Django 3.1.7 on 2021-06-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0009_auto_20210625_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tok',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='거래금액'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='잔액'),
        ),
    ]
