# Generated by Django 3.1.7 on 2021-07-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_account', '0010_auto_20210628_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='giver_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='주는사람 잔액'),
        ),
        migrations.AlterField(
            model_name='account',
            name='taker_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='받는사람 잔액'),
        ),
    ]
