# Generated by Django 3.1.7 on 2021-09-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBank_timeshop', '0003_recomment_mention'),
        ('TimeBank_account', '0010_auto_20210907_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='TimeBank_timeshop.product', verbose_name='중고거래글'),
        ),
    ]
